AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
    - config/**/*
    - lib/tasks/*
    - node_modules/**/*
    - log/**/*
    - tmp/**/*
  NewCops: enable
  SuggestExtensions: false
Layout/LineLength:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: "double_quotes"
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ParenthesesAroundCondition:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
