version: "3"
services:
  db:
    image: postgres:14.1-bullseye
    volumes:
      - trial-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/trial-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
volumes:
  trial-db-data:
    driver: local
